all:
	gcc ../../../multicast.c receiver.c -o recv && gcc ../../../multicast.c receiver1.c -o recv1 && gcc ../../../multicast.c send_test.c -o send && gcc ../../../multicast.c send_test1.c -o send1
clean:
	rm send send1 recv recv1
